<h4><?= $this->escape($this->name) ?>(<?= $this->escape($this->no) ?>)</h4>
<ol>
    <?php foreach (CompanyEvent::search(array('company_no' => $this->no)) as $event) { ?>
    <li>
    <?= date('Y/m/d', $event->time) ?>. <?= $this->escape($event->message) ?>
    <?php if ($event->from) { ?>
    [<a href="<?= $this->escape($event->from) ?>" target="_blank">來源</a>]
    <?php } ?>
    <?php if ($eent->snapshot) { ?>
    [<a href="<?= $this->escape($event->snapshot) ?>" target="_blank">截圖</a>]
    <?php } ?>
    </li>
    <?php } ?>
</ol>
