<h4><?= $this->escape($this->name) ?>(<?= $this->escape($this->no) ?>)</h4>
<?php foreach (CompanyEvent::search(array('company_no' => $this->no)) as $event) { ?>
<?php if ($event->type == 1) { ?>
<?php $data = json_decode($event->data) ?>
違反法令條款: <?= $this->escape($data->{'違反法令條款'}) ?><br>
處分書文號: <?= $this->escape($data->{'處分書文號'}) ?><br>
處分日期: <?= $this->escape($data->{'處分日期'}) ?><br>
<hr>
<?php } ?>
<?php } ?>
