<?= $this->partial('/common/header.phtml', $this) ?>
<table class="table">
    <thead>
        <tr>
            <td>資料包名稱</td>
            <td>上傳人</td>
            <td>最近更新時間</td>
        </tr>
    </thead>
    <tbody>
    <?php foreach (Package::search(1) as $package) { ?>
    <tr>
        <td><a href="/package/show/<?= $package->package_id ?>"><?= $this->escape($package->name) ?></a></td>
        <td><?= $this->escape($package->team->name) ?></td>
        <td><?= $this->partial('/helper/counttime.phtml', array('time' => $package->package_time)) ?></td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<?= $this->partial('/common/footer.phtml', $this) ?>
