<?php
$this->og_image = 'http://' . $_SERVER['HTTP_HOST'] . '/static/104.png';
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<h1>求職小幫手</h1>

<div style="clear: both">
    <p class="lead" style="float: left">
    求職小幫手是一個瀏覽器套件，安裝之後當你在瀏覽像是 <a href="http://www.104.com.tw/" target="_blank">104</a>, <a href="http://www.1111.com.tw" target="_blank">1111</a>, <a href="http://www.yes123.com.tw" target="_blank">yes123</a>, <a href="http://www.518.com.tw" target="_blank">518</a>, <a href="http://www.ejob.gov.tw" target="_blank">ejob</a> 等求職網站時，他會自動告訴你一些求職網站不會主動告訴你的事情（例如：這家公司最近是否有因為違反勞基法被罰錢），讓你有更多面向可以評價你要選擇的公司。
    </p>
    <img style="float: left" src="/static/104.png" width="557" height="339">
    <div style="clear: both"></div>
</div>

<h3>如果你是求職者</h3>
<p>現在就馬上到 <a href="https://chrome.google.com/webstore/detail/%E6%B1%82%E8%81%B7%E5%B0%8F%E5%B9%AB%E6%89%8B/bjolfofcjiolhmlaoebndilgbhonclcn" target="_blank">Chrome 線上應用程式商店</a> 安裝求職小幫手吧！裝完後你在瀏覽求職網站就會看到網址列多一個「職」的圖示，點進去就可以選擇你想要什麼樣的名單。</p>
<p>裝完求職小幫手之後，試試看到 <a href="http://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=504e462d383a445a35363e6756423a1d0483e466f504a42252525256a3d552a29745j48&jobsource=n104bank1" rel="nofollow">這裡</a> 看看求職小幫手會不會告訴你這家公司違反勞基法的記錄吧!</p>
<p>若有遇到任何問題（例如：公司在勞委會罰錢名單，卻未跳出黃色警示訊息，或者正好相反...），或者有任何建議，歡迎到 <a href="https://groups.google.com/forum/?fromgroups=#!forum/twjobhelper">討論區</a> 分享</p>

<h3>想要直接搜尋公司有沒有違反勞基法記錄?</h3>
到 <a href="https://jobhelper.g0v.ronny.tw/mobile/">https://jobhelper.g0v.ronny.tw/mobile/</a> 就可以搜尋囉!

<hr>
<h3>資料表清單</h3>
<table class="table">
    <thead>
        <tr>
            <td>資料包名稱</td>
            <td>上傳人</td>
            <td>最近更新時間</td>
        </tr>
    </thead>
    <tbody>
    <?php foreach (Package::search(array('status' => 0)) as $package) { ?>
    <tr>
        <td><a href="/package/show/<?= $package->package_id ?>"><?= $this->escape($package->name) ?></a></td>
        <td><?= $this->escape($package->team->name) ?></td>
        <td><?= $this->partial('/helper/counttime.phtml', array('time' => $package->package_time)) ?></td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<?= $this->partial('/common/footer.phtml', $this) ?>
