<?= $this->partial('/common/header.phtml', $this) ?>
<h3>資料包管理</h3>
<table class="table">
    <thead>
        <tr>
            <td>名稱</td>
            <td>建立時間</td>
            <td>更新時間</td>
        </tr>
    </thead>
    <tbody>
    <?php foreach (Package::search(array('team_id' => $this->team->team_id)) as $package) { ?>
    <tr>
        <td><a href="/panel/showpackage/<?= $package->package_id ?>"><?= $this->escape($package->name) ?></a></td>
        <td><?= $this->partial('/helper/counttime.phtml', array('time' => $package->created_at)) ?></td>
        <td><?= $this->partial('/helper/counttime.phtml', array('time' => $package->updated_at)) ?></td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<h4>新增資料包</h4>
<form method="post" action="/panel/newpackage">
    <input type="hidden" name="sToken" value="<?= $this->sToken ?>">
    名稱 <input type="text" name="name"><br>
    說明: <textarea name="note"></textarea>
    <button type="submit">送出</button>
</form>
<?= $this->partial('/common/footer.phtml', $this) ?>
