<?= $this->partial('/common/header.phtml', $this) ?>
<h3>資料包管理</h3>
<form method="post" action="/panel/editpackage/<?= $this->package->package_id ?>">
    <input type="hidden" name="sToken" value="<?= $this->sToken ?>">
    名稱: <input type="text" name="name" value="<?= $this->escape($this->package->name) ?>"><br>
    說明: (請加入「資料來源」、「更新頻率」、「資訊取得方式」、「資料錯誤連絡方式」等資訊)<br>
    <textarea class="span12" name="note" cols="80" rows="6"><?= $this->escape($this->package->note) ?></textarea><br>
    <button type="submit">修改</button>
</form>
<hr>
<h3>可以管理這個資料包的名單</h3>
<ol>
    <?php foreach (TeamPackage::search(array('package_id' => $this->package->package_id)) as $team_package) { ?>
    <li><?= $this->escape($team_package->team->name) ?></li>
    <?php } ?>
    <li>
    <form method="post" action="/panel/newpackageteam/<?= $this->package->package_id ?>">
        <input type="hidden" name="sToken" value="<?= $this->sToken ?>">
        選擇團體: <select name="team_id">
            <option>請選擇要增加的群組</option>
            <?php foreach (Team::search(1) as $team) { ?>
            <option value="<?= $team->team_id ?>"><?= $this->escape($team->name) ?></option>
            <?php } ?>
        </select>
        <button type="submit">新增</button>
    </form>
    </li>
</ol>
<h3>更新資料包內容</h3>
<form method="post" action="/panel/showpackage/<?= $this->package->package_id ?>?action=updatecontent">
    <input type="hidden" name="sToken" value="<?= $this->sToken ?>">
    請貼上 CSV 內容，欄位分別為 [公司名稱],[事件日期],[說明原因],[原始連結],[截圖連結]<br>
    Ex: <code>台灣麥當勞餐廳股份有限公司,2012/12/7,違反勞基法第24條(延長工作時間未依規定加給工資)　北府勞條字第1013064746號函,http://www.labor.ntpc.gov.tw/_file/1075/SG/46207/D.html,,</code><br>
    <textarea class="span12" name="content" cols="80" rows="6"><?= $this->escape($this->content ?: $this->package->content->content) ?></textarea>
    <button type="submit">修改</button>
</form>
<?php if ($this->error_message) { ?>
<script>alert(<?= json_encode($this->error_message) ?>); </script>
<?php } ?>
<?= $this->partial('/common/footer.phtml', $this) ?>
