<?= $this->partial('/common/header.phtml', $this) ?>
<h3>群組資訊</h3>
<form method="post" action="/panel/team">
    <input type="hidden" name="sToken" value="<?= $this->sToken ?>">
    名稱: <input type="text" name="name" value="<?= $this->escape($this->team->name) ?>"><br>
    群組資料及連絡方式: <textarea name="note"><?= $this->escape($this->team->note) ?></textarea><br>
    <button type="submit">修改</button>
</form>
<h3>群組成員</h3>
<ul>
    <?php foreach (TeamMember::search(array('team_id' => $this->team->team_id)) as $member) { ?>
    <li><?= $this->escape($member->user->user_name) ?></li>
    <?php } ?>
    <li>
    <form method="post" action="/panel/addteammember/<?= $this->team->team_id ?>">
        <input type="hidden" name="sToken" value="<?= $this->sToken ?>">
        帳號: <input type="text" name="user_name" placeholder="請輸入 google://[gmail信箱]"><br>
        <button type="submit">新增</button>
    </form>
    </li>
</ul>
<h3>資料包管理</h3>
<table class="table">
    <thead>
        <tr>
            <td>名稱</td>
            <td>狀態</td>
            <td>建立時間</td>
            <td>更新時間</td>
        </tr>
    </thead>
    <tbody>
    <?php foreach (TeamPackage::search(array('team_id' => $this->team->team_id)) as $team_package) { ?>
    <?php $package = $team_package->package; ?>
    <tr>
        <td><a href="/panel/showpackage/<?= $package->package_id ?>"><?= $this->escape($package->name) ?></a></td>
        <td><?= $package->status == 0 ? '線上' : '測試' ?></td>
        <td><?= $this->partial('/helper/counttime.phtml', array('time' => $package->created_at)) ?></td>
        <td><?= $this->partial('/helper/counttime.phtml', array('time' => $package->updated_at)) ?></td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<h4>新增資料包</h4>
<form method="post" action="/panel/newpackage/<?= $this->team->team_id ?>">
    <input type="hidden" name="sToken" value="<?= $this->sToken ?>">
    名稱 <input type="text" name="name"><br>
    說明: <textarea name="note"></textarea><br>
    狀態: 
    <label><input type="radio" name="status" value="1" checked="checked">測試</label>
    <label><input type="radio" name="status" value="0">線上</label>
    <button type="submit">送出</button>
</form>

        
<?= $this->partial('/common/footer.phtml', $this) ?>
