<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="icon" href="static/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="static/favicon.ico" type="image/x-icon"/>

<?php if ($this->title) { ?>
<title><?= $this->escape($this->title) ?> - 求職小幫手</title>
<?php } else { ?>
<title>求職小幫手</title>
<?php } ?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/bootstrap.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/css/bootstrap.css">
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="/">求職小幫手</a>
        <ul class="nav">
            <li>
            <a href="/">首頁</a>
            </li>
            <li>
            <a href="https://chrome.google.com/webstore/detail/%E6%B1%82%E8%81%B7%E5%B0%8F%E5%B9%AB%E6%89%8B/bjolfofcjiolhmlaoebndilgbhonclcn" target="_blank">Chrome下載</a>
            </li>
            <li>
            <a href="https://addons.mozilla.org/zh-TW/firefox/addon/job-helper/">Firefox下載</a>
            </li>
            <li>
            <a href="/mobile">手機版</a>
            </li>
            <li>
            <a href="https://groups.google.com/forum/?fromgroups=#!forum/twjobhelper" target="_blank">討論區</a>
            </li>
            <li>
            <a href="https://www.facebook.com/twjobhelper" target="_blank">粉絲專頁</a>
            </li>
            <li>
            <a href="http://ronnywang.pixnet.net/blog" target="_blank">@ronnywang</a>
            </li>
            <?php if ($this->user) { ?>
            <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Hi! <?= $this->escape($this->user->user_name) ?><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <?php foreach ($this->user->user_teams as $user_team) { ?>
                <li><a href="/panel/team/<?= $user_team->team_id ?>"><?= $this->escape($user_team->team->name) ?></a></li>
                <?php } ?>
                <li class="divider"></li>
                <li><a href="/login/logout">登出</a></li>
            </ul>
            </li>
            <?php } else { ?>
            <li>
            <a href="/login/google">登入</a>
            </li>
            <?php } ?>
        </ul>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
